# Generated by Django 2.2.1 on 2019-07-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Example2',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(null=True, upload_to='media/')),
                ('delete', models.BooleanField(default=False)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.Example2')),
            ],
            options={
                'db_table': 'Example',
            },
        ),
    ]
