# Generated by Django 2.2.1 on 2019-07-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_auto_20190712_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='media/')),
                ('relacion_usuario', models.IntegerField()),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
    ]
