# Generated by Django 2.2.1 on 2019-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='type_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
