# Generated by Django 2.2.1 on 2019-07-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petcitas', '0002_auto_20190723_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citas',
            new_name='Cita',
        ),
        migrations.RenameModel(
            old_name='Mascotas',
            new_name='Mascota',
        ),
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
        migrations.AlterModelTable(
            name='cita',
            table='cita',
        ),
        migrations.AlterModelTable(
            name='mascota',
            table='pet',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
