# Generated by Django 2.2.1 on 2019-07-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petcitas', '0003_auto_20190723_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='type_id',
            field=models.IntegerField(),
        ),
    ]
